version: '3'

services:
    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        restart: unless-stopped
        ports:
            - 80:80
        environment:
            - EMAIL=ta@mail.com
            - DOMAINS=best.com
        volumes:
            - /var/www/certbot/:/var/www/certbot/
            - ./nginx/letsencrypt/:/etc/letsencrypt/
