version: '3'

x-security-base: &x-security-base
    # import directive <<: *x-security-base
    # import values *x-security-base
#    user: "1000:1000"
    pids_limit: 100
    cpus: 0.5 # 0.0 - 1 - this 1 core
    mem_limit: 100m # Override per container if necessary
    security_opt:
        - no-new-privileges=true
    logging:
        options:
            max-size: "10m"
            max-file: "3"

services:
    nginx:
        <<: *x-security-base
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        restart: unless-stopped
        ports:
            - 80:80
        environment:
            - EMAIL=ta@mail.com
            - DOMAINS=best.com
        volumes:
            - /var/www/certbot/:/var/www/certbot/
            - ./nginx/letsencrypt/:/etc/letsencrypt/
        logging:
            # Redirect to systemd for other services (fail2ban)
            driver: journald
            options:
                # "{{.ImageName}}/{{.Name}}/{{.ID}}"
                tag: "nginx-80"

